# SPDX-License-Identifier: ISC

obj-$(CONFIG_MT7927_COMMON) += mt7927-common.o
obj-$(CONFIG_MT7927E) += mt7927e.o
obj-$(CONFIG_MT7927U) += mt7927u.o

mt7927-common-y := mac.o mcu.o main.o init.o debugfs.o
mt7927e-y := pci.o pci_mac.o pci_mcu.o
mt7927u-y := usb.o
